__project__:
  args: /home/tgenjetstream/jetstream_centro/venv/bin/jetstream init /scratch/tgenjetstream/centro/projects/JA20035_CVAX001_25b86d3c25
    -C /home/tgenjetstream/jetstream_centro/data/config_files/JA20035_CVAX001_25b86d3c25.json
  datetime: '2021-05-03T22:08:19.510587'
  hostname: dback-login3
  id: 01F4T4CSHP4R6XKDZ677FM9Q67
  note: init
  pwd: /home/tgenjetstream/jetstream_centro
  user: tgenjetstream
  version: 1.6.1
cram: true
dataFiles:
- assayCode: ILSMR
  dnaRnaMergeKey: JA20035_CVAX001_1_PB_Whole
  fastqCode: R1
  fastqPath: /labs/altin/fastq_DoNotTouch/210430_A00674_0267_BH3G2VDSX2/Project_JA20035_CVAX001_1_ILSMR/Sample_JA20035_CVAX001_1_PB_Whole_C1_ILSMR_L36211_H3G2VDSX2/JA20035_CVAX001_1_PB_Whole_C1_ILSMR_L36211_H3G2VDSX2_AACCATAGAA_L003_R1_001.fastq.gz
  fileType: fastq
  fraction: Whole
  glPrep: RNA
  glType: RNA
  index1Length: 11
  index2Length: 11
  limsLibraryRecordId: 96437
  numberOfReads: 159712212
  read1Length: 101
  read2Length: 101
  readOrientation: Inward
  rgbc: AACCATAGAA-CCATCTCGCC
  rgcn: TGen
  rgid: H3G2VDSX2_3_AACCATAGAA-CCATCTCGCC
  rglb: L36211
  rgpl: ILLUMINA
  rgpm: NovaSeq6000
  rgpu: H3G2VDSX2_3
  rgsm: JA20035_CVAX001_1_PB_Whole_C1
  rnaStrandDirection: Reverse
  rnaStrandType: Stranded
  sampleMergeKey: JA20035_CVAX001_1_PB_Whole_C1_ILSMR
  sampleName: JA20035_CVAX001_1_PB_Whole_C1_ILSMR_L36211
  subGroup: Constitutional
  umiInLine: 'false'
  umiLength: 0
  umiRead: false
- assayCode: ILSMR
  dnaRnaMergeKey: JA20035_CVAX001_1_PB_Whole
  fastqCode: R2
  fastqPath: /labs/altin/fastq_DoNotTouch/210430_A00674_0267_BH3G2VDSX2/Project_JA20035_CVAX001_1_ILSMR/Sample_JA20035_CVAX001_1_PB_Whole_C1_ILSMR_L36211_H3G2VDSX2/JA20035_CVAX001_1_PB_Whole_C1_ILSMR_L36211_H3G2VDSX2_AACCATAGAA_L003_R2_001.fastq.gz
  fileType: fastq
  fraction: Whole
  glPrep: RNA
  glType: RNA
  index1Length: 11
  index2Length: 11
  limsLibraryRecordId: 96437
  numberOfReads: 159712212
  read1Length: 101
  read2Length: 101
  readOrientation: Inward
  rgbc: AACCATAGAA-CCATCTCGCC
  rgcn: TGen
  rgid: H3G2VDSX2_3_AACCATAGAA-CCATCTCGCC
  rglb: L36211
  rgpl: ILLUMINA
  rgpm: NovaSeq6000
  rgpu: H3G2VDSX2_3
  rgsm: JA20035_CVAX001_1_PB_Whole_C1
  rnaStrandDirection: Reverse
  rnaStrandType: Stranded
  sampleMergeKey: JA20035_CVAX001_1_PB_Whole_C1_ILSMR
  sampleName: JA20035_CVAX001_1_PB_Whole_C1_ILSMR_L36211
  subGroup: Constitutional
  umiInLine: 'false'
  umiLength: 0
  umiRead: false
- assayCode: ILSMR
  dnaRnaMergeKey: JA20035_CVAX001_1_PB_Whole
  fastqCode: R1
  fastqPath: /labs/altin/fastq_DoNotTouch/210430_A00674_0267_BH3G2VDSX2/Project_JA20035_CVAX001_1_ILSMR/Sample_JA20035_CVAX001_1_PB_Whole_C2_ILSMR_L36212_H3G2VDSX2/JA20035_CVAX001_1_PB_Whole_C2_ILSMR_L36212_H3G2VDSX2_GGTTGCGAGG_L003_R1_001.fastq.gz
  fileType: fastq
  fraction: Whole
  glPrep: RNA
  glType: RNA
  index1Length: 11
  index2Length: 11
  limsLibraryRecordId: 96438
  numberOfReads: 140761908
  read1Length: 101
  read2Length: 101
  readOrientation: Inward
  rgbc: GGTTGCGAGG-TTGCTCTATT
  rgcn: TGen
  rgid: H3G2VDSX2_3_GGTTGCGAGG-TTGCTCTATT
  rglb: L36212
  rgpl: ILLUMINA
  rgpm: NovaSeq6000
  rgpu: H3G2VDSX2_3
  rgsm: JA20035_CVAX001_1_PB_Whole_C2
  rnaStrandDirection: Reverse
  rnaStrandType: Stranded
  sampleMergeKey: JA20035_CVAX001_1_PB_Whole_C2_ILSMR
  sampleName: JA20035_CVAX001_1_PB_Whole_C2_ILSMR_L36212
  subGroup: Constitutional
  umiInLine: 'false'
  umiLength: 0
  umiRead: false
- assayCode: ILSMR
  dnaRnaMergeKey: JA20035_CVAX001_1_PB_Whole
  fastqCode: R2
  fastqPath: /labs/altin/fastq_DoNotTouch/210430_A00674_0267_BH3G2VDSX2/Project_JA20035_CVAX001_1_ILSMR/Sample_JA20035_CVAX001_1_PB_Whole_C2_ILSMR_L36212_H3G2VDSX2/JA20035_CVAX001_1_PB_Whole_C2_ILSMR_L36212_H3G2VDSX2_GGTTGCGAGG_L003_R2_001.fastq.gz
  fileType: fastq
  fraction: Whole
  glPrep: RNA
  glType: RNA
  index1Length: 11
  index2Length: 11
  limsLibraryRecordId: 96438
  numberOfReads: 140761908
  read1Length: 101
  read2Length: 101
  readOrientation: Inward
  rgbc: GGTTGCGAGG-TTGCTCTATT
  rgcn: TGen
  rgid: H3G2VDSX2_3_GGTTGCGAGG-TTGCTCTATT
  rglb: L36212
  rgpl: ILLUMINA
  rgpm: NovaSeq6000
  rgpu: H3G2VDSX2_3
  rgsm: JA20035_CVAX001_1_PB_Whole_C2
  rnaStrandDirection: Reverse
  rnaStrandType: Stranded
  sampleMergeKey: JA20035_CVAX001_1_PB_Whole_C2_ILSMR
  sampleName: JA20035_CVAX001_1_PB_Whole_C2_ILSMR_L36212
  subGroup: Constitutional
  umiInLine: 'false'
  umiLength: 0
  umiRead: false
dnaAlignmentStyle: tgen
email: denriquez@tgen.org,aboyle@tgen.org
ethnicity: Unknown
familyCode: ''
holdConfig: false
hpcAccount: tgen-367000
isilonPath: /labs/altin/Pipeline_Results_Temp_Storage/
matchedNormal: false
matchedNormalToUse: ''
maternalID: ''
pairoscope_call_requirement: 4
patCode: CVAX001
paternalID: ''
pipeline: phoenix@v1.1.2
project: JA20035_CVAX001
sex: Female
study: JA20035
studyDisease: ''
submissionSource: TGenLIMS
submitter: enriquez
tasks:
  CHIP_quality_control_stats_bam_coverage: true
  CHIP_quality_control_stats_compute_GCBias: true
  CHIP_quality_control_stats_macs2_callpeak: true
  CHIP_quality_control_stats_multi_big_wig_summary: true
  CHIP_quality_control_stats_plot_coverage: true
  CHIP_quality_control_stats_plot_fingerprint: true
  Exome_alignment_base_recalibration_gatk: false
  Exome_alignment_mark_duplicates_gatk: false
  Exome_alignment_mark_duplicates_samblaster: false
  Exome_alignment_mark_duplicates_samtools: true
  Exome_constitutional_annotate_vcfs_bcftools_clinvar: true
  Exome_constitutional_annotate_vcfs_bcftools_cosmic_coding: true
  Exome_constitutional_annotate_vcfs_bcftools_cosmic_noncoding: true
  Exome_constitutional_annotate_vcfs_bcftools_dbsnp: true
  Exome_constitutional_annotate_vcfs_bcftools_gnomad_exome: true
  Exome_constitutional_annotate_vcfs_bcftools_gnomad_genome: true
  Exome_constitutional_annotate_vcfs_bcftools_topmed: true
  Exome_constitutional_annotate_vcfs_snpEff_ann: false
  Exome_constitutional_annotate_vcfs_vep: true
  Exome_constitutional_genotype_hc_gvcf_gatk_GenotypeGVCFs: false
  Exome_constitutional_snp_indel_caller_deepvariant: true
  Exome_constitutional_snp_indel_caller_freebayes: false
  Exome_constitutional_snp_indel_caller_gatk_HaplotypeCaller: true
  Exome_constitutional_snp_indel_caller_octopus: false
  Exome_constitutional_snp_indel_caller_strelka2: false
  Exome_constitutional_structural_caller_manta: true
  Exome_disease_specific_multiple_myeloma: false
  Exome_quality_control_constitutional_contamination_check_VerifyBamID: true
  Exome_quality_control_constitutional_sex_check_freebayes: true
  Exome_quality_control_genotype_concordance_snpSniffer: true
  Exome_quality_control_stats_gatk_CollectHsMetrics: true
  Exome_quality_control_stats_gatk_CollectMultipleMetrics: false
  Exome_quality_control_stats_gatk_ConvertSequencingArtifactToOxoG: true
  Exome_quality_control_stats_samtools_flagstat: false
  Exome_quality_control_stats_samtools_idxstats: true
  Exome_quality_control_stats_samtools_markdup_stats: true
  Exome_quality_control_stats_samtools_stats: true
  Exome_somatic_annotate_vcfs_bcftools_clinvar: true
  Exome_somatic_annotate_vcfs_bcftools_cosmic_coding: true
  Exome_somatic_annotate_vcfs_bcftools_cosmic_noncoding: true
  Exome_somatic_annotate_vcfs_bcftools_dbsnp: true
  Exome_somatic_annotate_vcfs_bcftools_gnomad_exome: true
  Exome_somatic_annotate_vcfs_bcftools_gnomad_genome: true
  Exome_somatic_annotate_vcfs_bcftools_topmed: true
  Exome_somatic_annotate_vcfs_snpEff_ann: false
  Exome_somatic_annotate_vcfs_vep: true
  Exome_somatic_cna_caller_gatk: true
  Exome_somatic_merge_vcfs_vcfMerger2: true
  Exome_somatic_sample_metric_msisensor_pro: true
  Exome_somatic_sample_metric_tgen_mutation_burden: true
  Exome_somatic_snp_indel_caller_VarDict: true
  Exome_somatic_snp_indel_caller_gatk_mutect2: true
  Exome_somatic_snp_indel_caller_lancet: true
  Exome_somatic_snp_indel_caller_octopus: true
  Exome_somatic_snp_indel_caller_strelka2: false
  Exome_somatic_structural_caller_delly: false
  Exome_somatic_structural_caller_manta: true
  Exome_tumor_only_annotate_vcfs_bcftools_clinvar: false
  Exome_tumor_only_annotate_vcfs_bcftools_cosmic_coding: false
  Exome_tumor_only_annotate_vcfs_bcftools_cosmic_noncoding: false
  Exome_tumor_only_annotate_vcfs_bcftools_dbsnp: false
  Exome_tumor_only_annotate_vcfs_bcftools_gnomad_exome: false
  Exome_tumor_only_annotate_vcfs_bcftools_gnomad_genome: false
  Exome_tumor_only_annotate_vcfs_bcftools_topmed: false
  Exome_tumor_only_annotate_vcfs_snpEff_ann: false
  Exome_tumor_only_annotate_vcfs_vep: false
  Exome_tumor_only_cna_caller_gatk: false
  Exome_tumor_only_merge_vcfs_vcfMerger2: false
  Exome_tumor_only_snp_indel_caller_VarDict: false
  Exome_tumor_only_snp_indel_caller_deepvariant: false
  Exome_tumor_only_snp_indel_caller_gatk_mutect2: false
  Exome_tumor_only_snp_indel_caller_lancet: false
  Exome_tumor_only_snp_indel_caller_lumosvar2: false
  Exome_tumor_only_snp_indel_caller_octopus: false
  Exome_tumor_only_snp_indel_caller_strelka2: false
  Exome_tumor_only_structural_caller_delly: false
  Exome_tumor_only_structural_caller_manta: false
  Genome_alignment_base_recalibration_gatk: false
  Genome_alignment_mark_duplicates_gatk: false
  Genome_alignment_mark_duplicates_samblaster: false
  Genome_alignment_mark_duplicates_samtools: true
  Genome_constitutional_annotate_vcfs_bcftools_clinvar: true
  Genome_constitutional_annotate_vcfs_bcftools_cosmic_coding: true
  Genome_constitutional_annotate_vcfs_bcftools_cosmic_noncoding: true
  Genome_constitutional_annotate_vcfs_bcftools_dbsnp: true
  Genome_constitutional_annotate_vcfs_bcftools_gnomad_exome: true
  Genome_constitutional_annotate_vcfs_bcftools_gnomad_genome: true
  Genome_constitutional_annotate_vcfs_bcftools_topmed: true
  Genome_constitutional_annotate_vcfs_snpEff_ann: false
  Genome_constitutional_annotate_vcfs_vep: true
  Genome_constitutional_cna_caller_ichor: true
  Genome_constitutional_genotype_hc_gvcf_gatk_GenotypeGVCFs: false
  Genome_constitutional_snp_indel_caller_deepvariant: true
  Genome_constitutional_snp_indel_caller_freebayes: false
  Genome_constitutional_snp_indel_caller_gatk_HaplotypeCaller: true
  Genome_constitutional_snp_indel_caller_octopus: false
  Genome_constitutional_snp_indel_caller_strelka2: false
  Genome_constitutional_structural_caller_manta: true
  Genome_disease_specific_multiple_myeloma: false
  Genome_quality_control_constitutional_contamination_check_VerifyBamID: true
  Genome_quality_control_constitutional_sex_check_freebayes: true
  Genome_quality_control_genotype_concordance_snpSniffer: true
  Genome_quality_control_stats_gatk_CollectMultipleMetrics: false
  Genome_quality_control_stats_gatk_CollectRawWgsMetrics: false
  Genome_quality_control_stats_gatk_CollectWgsMetrics: false
  Genome_quality_control_stats_gatk_CollectWgsMetricsWithNonZeroCoverage: false
  Genome_quality_control_stats_gatk_ConvertSequencingArtifactToOxoG: true
  Genome_quality_control_stats_samtools_flagstat: false
  Genome_quality_control_stats_samtools_idxstats: true
  Genome_quality_control_stats_samtools_markdup_stats: true
  Genome_quality_control_stats_samtools_stats: true
  Genome_somatic_annotate_vcfs_bcftools_clinvar: true
  Genome_somatic_annotate_vcfs_bcftools_cosmic_coding: true
  Genome_somatic_annotate_vcfs_bcftools_cosmic_noncoding: true
  Genome_somatic_annotate_vcfs_bcftools_dbsnp: true
  Genome_somatic_annotate_vcfs_bcftools_gnomad_exome: true
  Genome_somatic_annotate_vcfs_bcftools_gnomad_genome: true
  Genome_somatic_annotate_vcfs_bcftools_topmed: true
  Genome_somatic_annotate_vcfs_snpEff_ann: false
  Genome_somatic_annotate_vcfs_vep: true
  Genome_somatic_cna_caller_gatk: true
  Genome_somatic_merge_vcfs_vcfMerger2: true
  Genome_somatic_sample_metric_msisensor_pro: true
  Genome_somatic_sample_metric_tgen_mutation_burden: true
  Genome_somatic_snp_indel_caller_VarDict: true
  Genome_somatic_snp_indel_caller_gatk_mutect2: true
  Genome_somatic_snp_indel_caller_lancet: false
  Genome_somatic_snp_indel_caller_octopus: true
  Genome_somatic_snp_indel_caller_strelka2: false
  Genome_somatic_structural_caller_delly: false
  Genome_somatic_structural_caller_manta: true
  Genome_tumor_only_annotate_vcfs_bcftools_clinvar: false
  Genome_tumor_only_annotate_vcfs_bcftools_cosmic_coding: false
  Genome_tumor_only_annotate_vcfs_bcftools_cosmic_noncoding: false
  Genome_tumor_only_annotate_vcfs_bcftools_dbsnp: false
  Genome_tumor_only_annotate_vcfs_bcftools_gnomad_exome: false
  Genome_tumor_only_annotate_vcfs_bcftools_gnomad_genome: false
  Genome_tumor_only_annotate_vcfs_bcftools_topmed: false
  Genome_tumor_only_annotate_vcfs_snpEff_ann: false
  Genome_tumor_only_annotate_vcfs_vep: false
  Genome_tumor_only_cna_caller_gatk: false
  Genome_tumor_only_merge_vcfs_vcfMerger2: false
  Genome_tumor_only_snp_indel_caller_VarDict: false
  Genome_tumor_only_snp_indel_caller_deepvariant: false
  Genome_tumor_only_snp_indel_caller_gatk_mutect2: false
  Genome_tumor_only_snp_indel_caller_lancet: false
  Genome_tumor_only_snp_indel_caller_octopus: false
  Genome_tumor_only_snp_indel_caller_strelka2: false
  Genome_tumor_only_structural_caller_delly: false
  Genome_tumor_only_structural_caller_manta: false
  RNA_alignment_rna_alignment_STAR: true
  RNA_quality_control_genotype_concordance_snpSniffer: true
  RNA_quality_control_stats_gatk_CollectMultipleMetrics: false
  RNA_quality_control_stats_gatk_CollectRnaSeqMetrics: true
  RNA_quality_control_stats_gatk_ConvertSequencingArtifactToOxoG: false
  RNA_quality_control_stats_samtools_flagstat: false
  RNA_quality_control_stats_samtools_idxstats: true
  RNA_quality_control_stats_samtools_stats: true
  RNA_sample_metric_sample_metric_samtools_bedcov: true
  RNA_transcriptome_fusion_caller_Keep_STAR_Fusion_BAM: false
  RNA_transcriptome_fusion_caller_STAR_Fusion: true
  RNA_transcriptome_quantify_expression_HTseq: true
  RNA_transcriptome_quantify_expression_RSEM: true
  RNA_transcriptome_quantify_expression_salmon_bam: false
  RNA_transcriptome_quantify_expression_salmon_fastqs: true
  RNA_transcriptome_quantify_expression_subread_featureCounts: true
  SingleCellRNA_VDJ_Assembly_cellranger_vdj: true
  SingleCellRNA_quality_control_genotype_concordance_snpSniffer: true
  SingleCellRNA_quality_control_stats_gatk_CollectMultipleMetrics: false
  SingleCellRNA_quality_control_stats_gatk_CollectRnaSeqMetrics: true
  SingleCellRNA_quality_control_stats_gatk_ConvertSequencingArtifactToOxoG: false
  SingleCellRNA_quality_control_stats_samtools_flagstat: false
  SingleCellRNA_quality_control_stats_samtools_idxstats: true
  SingleCellRNA_quality_control_stats_samtools_stats: true
  SingleCellRNA_sample_metric_sample_metric_samtools_bedcov: true
  SingleCellRNA_transcriptome_quantify_expression_STARsolo: true
  SingleCellRNA_transcriptome_quantify_expression_cellranger_count: true
varDB: false
wesAssayToPair: ''
